---
title: "R Lab Practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- c(1,2,3,4)
x
```

```{r}
y= c(1,2,3)
y
```

```{r}
ls()
rm(list=ls())
ls()
```

```{r}
x=matrix(c(1,2,3,4),2,2,byrow=TRUE)
x
```

```{r}
set.seed(3)
y=rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

```{r}
pdf("Figure.pdf")
plot(x,y,col="green")
dev.off() #use when we're done making a plot
```

```{r}
x=seq(1,10)
x
x=1:10
```

```{r}
y=x
f=outer(x,y,function (x,y)cos(y)/(1+x^2))
contour (x,y,f)
contour(x,y,f,nlevels=45,add=T)
fa=(f-t(f))/2
contour(x,y,fa,nlevels=15)
```

```{r}
image(x,y,fa)
persp(x,y,fa)
persp(x,y,fa,theta=30)
persp(x,y,fa,theta=30,phi=20) 
persp(x,y,fa,theta=30,phi=70) 
persp(x,y,fa,theta=30,phi=40)
```

```{r}
A=matrix(1:16,4,4)
A[2,3]
```

```{r}
A[c(1,3),c(2,4)]
```

```{r}
A[1:2,]
```

```{r}
A[,1:2]
```

```{r}
A[1,]
```

```{r}
A[-c(1,3),]
```

```{r}
dim(A)
```

```{r}
library(ISLR)
getwd()
setwd("~/Desktop/Denison/DA/DA 350")
Auto=read.table("Auto.data")
```

```{r}
Auto=read.table("Auto.data",header=T,na.strings="?")
```

